"use client"

import { motion } from "framer-motion"
import { Cookie, Shield, Settings, BarChart3, Users, Globe } from "lucide-react"
import Link from "next/link"

export default function CookiePolicyPage() {
  return (
    <div className="min-h-screen pt-20">
      {/* Hero Section */}
      <div className="relative bg-gradient-to-br from-dark via-secondary to-dark py-20 overflow-hidden">
        {/* Background Pattern */}
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#ffffff05_1px,transparent_1px),linear-gradient(to_bottom,#ffffff05_1px,transparent_1px)] bg-[size:4rem_4rem]" />

        <div className="relative max-w-7xl mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center space-y-6"
          >
            <div className="inline-flex items-center gap-2 px-5 py-2 rounded-full bg-primary/10 border border-primary/30 text-primary backdrop-blur-sm">
              <Cookie className="w-4 h-4" />
              <span className="font-semibold text-sm uppercase tracking-wide">Legal</span>
            </div>

            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold font-dm-sans text-white">
              Cookie Policy
            </h1>

            <p className="text-lg text-white/70 max-w-2xl mx-auto">
              Last updated: November 3rd, 2025
            </p>
          </motion.div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-5xl mx-auto px-4 py-16">
        {/* Introduction */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="prose prose-lg max-w-none mb-12"
        >
          <p className="text-grey leading-relaxed text-lg">
            This Cookie Policy explains how Core Innovate IT Ltd and its affiliates (collectively &quot;Core Innovate IT&quot;, &quot;we&quot;, &quot;us&quot;, and &quot;ours&quot;), use cookies and similar technologies to recognize you when you visit our website. It explains what these technologies are and why we use them, as well as the choices for how to control them.
          </p>
        </motion.div>

        {/* Main Sections */}
        <div className="space-y-8">

          {/* Definitions */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="relative bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10"
          >
            <h2 className="text-2xl font-bold font-dm-sans text-white mb-6">
              Definitions and Key Terms
            </h2>

            <div className="space-y-4">
              <div className="pl-4 border-l-2 border-primary/30">
                <h3 className="text-lg font-semibold text-white mb-2">Cookie</h3>
                <p className="text-grey leading-relaxed">
                  Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
                </p>
              </div>

              <div className="pl-4 border-l-2 border-primary/30">
                <h3 className="text-lg font-semibold text-white mb-2">Company</h3>
                <p className="text-grey leading-relaxed">
                  When this policy mentions &quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our,&quot; it refers to Core Innovate IT Ltd, that is responsible for your information under this Cookie Policy.
                </p>
              </div>

              <div className="pl-4 border-l-2 border-primary/30">
                <h3 className="text-lg font-semibold text-white mb-2">Device</h3>
                <p className="text-grey leading-relaxed">
                  Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Core Innovate IT and use the services.
                </p>
              </div>

              <div className="pl-4 border-l-2 border-primary/30">
                <h3 className="text-lg font-semibold text-white mb-2">Personal Data</h3>
                <p className="text-grey leading-relaxed">
                  Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
                </p>
              </div>

              <div className="pl-4 border-l-2 border-primary/30">
                <h3 className="text-lg font-semibold text-white mb-2">Service</h3>
                <p className="text-grey leading-relaxed">
                  Refers to the service provided by Core Innovate IT Ltd as described in the relative terms (if available) and on this platform.
                </p>
              </div>

              <div className="pl-4 border-l-2 border-primary/30">
                <h3 className="text-lg font-semibold text-white mb-2">Third-party Service</h3>
                <p className="text-grey leading-relaxed">
                  Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
                </p>
              </div>

              <div className="pl-4 border-l-2 border-primary/30">
                <h3 className="text-lg font-semibold text-white mb-2">Website</h3>
                <p className="text-grey leading-relaxed">
                  Core Innovate IT&apos;s site, which can be accessed via this URL:{" "}
                  <a href="https://www.coreinnovateit.com" className="text-primary hover:text-cyan-400 transition-colors">
                    https://www.coreinnovateit.com
                  </a>
                </p>
              </div>

              <div className="pl-4 border-l-2 border-primary/30">
                <h3 className="text-lg font-semibold text-white mb-2">You</h3>
                <p className="text-grey leading-relaxed">
                  A person or entity that is registered with Core Innovate IT to use the Services.
                </p>
              </div>
            </div>
          </motion.div>

          {/* What is a cookie */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="relative bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10"
          >
            <div className="flex items-start gap-4">
              <div className="flex-shrink-0">
                <div className="w-12 h-12 bg-gradient-to-br from-primary to-cyan-500 rounded-xl flex items-center justify-center">
                  <Cookie className="w-6 h-6 text-white" />
                </div>
              </div>

              <div className="flex-1 space-y-4">
                <h2 className="text-2xl font-bold font-dm-sans text-white">
                  What is a Cookie?
                </h2>
                <p className="text-grey leading-relaxed">
                  A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, remember information about you such as your language preference or login information. They&apos;re completely safe and can&apos;t be used to run programs or deliver viruses to your device.
                </p>
              </div>
            </div>
          </motion.div>

          {/* Why we use cookies */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="relative bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10"
          >
            <div className="flex items-start gap-4">
              <div className="flex-shrink-0">
                <div className="w-12 h-12 bg-gradient-to-br from-primary to-cyan-500 rounded-xl flex items-center justify-center">
                  <Shield className="w-6 h-6 text-white" />
                </div>
              </div>

              <div className="flex-1 space-y-4">
                <h2 className="text-2xl font-bold font-dm-sans text-white">
                  Why Do We Use Cookies?
                </h2>
                <p className="text-grey leading-relaxed">
                  We use first party and/or third party cookies on our website for various purposes such as:
                </p>

                <ul className="space-y-2 ml-4">
                  <li className="flex items-start gap-3 text-grey">
                    <span className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" />
                    <span>To facilitate the operation and functionality of our website</span>
                  </li>
                  <li className="flex items-start gap-3 text-grey">
                    <span className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" />
                    <span>To improve your experience of our website and make navigating around them quicker and easier</span>
                  </li>
                  <li className="flex items-start gap-3 text-grey">
                    <span className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" />
                    <span>To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you</span>
                  </li>
                  <li className="flex items-start gap-3 text-grey">
                    <span className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" />
                    <span>To analyze how our website is used and how best we can customize it</span>
                  </li>
                  <li className="flex items-start gap-3 text-grey">
                    <span className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" />
                    <span>To identify future prospects and personalize marketing and sales interactions with it</span>
                  </li>
                  <li className="flex items-start gap-3 text-grey">
                    <span className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" />
                    <span>To facilitate the tailoring of online advertising to your interests</span>
                  </li>
                </ul>
              </div>
            </div>
          </motion.div>

          {/* Types of cookies */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="relative bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10"
          >
            <h2 className="text-2xl font-bold font-dm-sans text-white mb-6">
              What Type of Cookies Does Core Innovate IT Use?
            </h2>

            <p className="text-grey leading-relaxed mb-6">
              Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire after a few minutes while others may expire after multiple years.
            </p>

            <div className="space-y-6">
              {/* Essential Cookies */}
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0">
                  <div className="w-10 h-10 bg-gradient-to-br from-primary to-cyan-500 rounded-lg flex items-center justify-center">
                    <Settings className="w-5 h-5 text-white" />
                  </div>
                </div>
                <div className="flex-1">
                  <h3 className="text-xl font-semibold text-white mb-2">Essential Cookies</h3>
                  <p className="text-grey leading-relaxed">
                    We use essential cookies to make our website work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie preferences and accessibility. Without them you wouldn&apos;t be able to use basic services. You may disable these by changing your browser settings, but this may affect how the website functions.
                  </p>
                </div>
              </div>

              {/* Performance Cookies */}
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0">
                  <div className="w-10 h-10 bg-gradient-to-br from-primary to-cyan-500 rounded-lg flex items-center justify-center">
                    <BarChart3 className="w-5 h-5 text-white" />
                  </div>
                </div>
                <div className="flex-1">
                  <h3 className="text-xl font-semibold text-white mb-2">Performance and Functionality Cookies</h3>
                  <p className="text-grey leading-relaxed">
                    These cookies are used to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.
                  </p>
                </div>
              </div>

              {/* Marketing Cookies */}
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0">
                  <div className="w-10 h-10 bg-gradient-to-br from-primary to-cyan-500 rounded-lg flex items-center justify-center">
                    <Users className="w-5 h-5 text-white" />
                  </div>
                </div>
                <div className="flex-1">
                  <h3 className="text-xl font-semibold text-white mb-2">Marketing Cookies</h3>
                  <p className="text-grey leading-relaxed">
                    These account-based marketing cookies enable us to identify future prospects and personalize sales and marketing interactions with them.
                  </p>
                </div>
              </div>

              {/* Analytics Cookies */}
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0">
                  <div className="w-10 h-10 bg-gradient-to-br from-primary to-cyan-500 rounded-lg flex items-center justify-center">
                    <BarChart3 className="w-5 h-5 text-white" />
                  </div>
                </div>
                <div className="flex-1">
                  <h3 className="text-xl font-semibold text-white mb-2">Analytics and Customization Cookies</h3>
                  <p className="text-grey leading-relaxed mb-3">
                    These cookies collect information that is used to help us understand how our website is being used or how effective our marketing campaigns are, or to help us customize our website for you.
                  </p>
                  <p className="text-grey leading-relaxed">
                    We use cookies served by Google Analytics to collect limited data directly from end-user browsers to enable us to better understand your use of our website. Further information on how Google collects and uses this data can be found at:{" "}
                    <a href="https://www.google.com/policies/privacy/partners/" target="_blank" rel="noopener noreferrer" className="text-primary hover:text-cyan-400 transition-colors">
                      https://www.google.com/policies/privacy/partners/
                    </a>
                    . You can opt-out of all Google supported analytics on our website by visiting:{" "}
                    <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer" className="text-primary hover:text-cyan-400 transition-colors">
                      https://tools.google.com/dlpage/gaoptout
                    </a>
                  </p>
                </div>
              </div>

              {/* Social Media Cookies */}
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0">
                  <div className="w-10 h-10 bg-gradient-to-br from-primary to-cyan-500 rounded-lg flex items-center justify-center">
                    <Users className="w-5 h-5 text-white" />
                  </div>
                </div>
                <div className="flex-1">
                  <h3 className="text-xl font-semibold text-white mb-2">Social Media Cookies</h3>
                  <p className="text-grey leading-relaxed">
                    These cookies are used when you share information using a social media sharing button or &quot;like&quot; button on our site or you link your account or engage with our content on or through a social networking website such as Facebook, Twitter or Google+. The social network will record that you have done this. These cookies may also include certain code that has been placed on the platform to help track conversions from ads, optimize ads based on collected data, build targeted audiences for future ads, and remarket to qualified users who have already taken certain action on the platform.
                  </p>
                </div>
              </div>

              {/* Third Party Cookies */}
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0">
                  <div className="w-10 h-10 bg-gradient-to-br from-primary to-cyan-500 rounded-lg flex items-center justify-center">
                    <Globe className="w-5 h-5 text-white" />
                  </div>
                </div>
                <div className="flex-1">
                  <h3 className="text-xl font-semibold text-white mb-2">Third Party Cookies</h3>
                  <p className="text-grey leading-relaxed">
                    Some cookies that have been set on our website are not set on a first party basis by Core Innovate IT. The website can be embedded with content from third parties to serve advertising. These third party service providers may set their own cookies on your web browser. Third party service providers control many of the performance and functionality, advertising, marketing and analytics cookies described above. We do not control the use of these third party cookies as cookies can only be accessed by the third party that originally set them.
                  </p>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Managing Cookies */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="relative bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10"
          >
            <h2 className="text-2xl font-bold font-dm-sans text-white mb-4">
              How You Can Manage Cookies?
            </h2>
            <p className="text-grey leading-relaxed mb-6">
              Most browsers allow you to control cookies through their &apos;settings&apos; preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information.
            </p>

            <h3 className="text-xl font-semibold text-white mb-3">Browser Help Pages</h3>
            <p className="text-grey leading-relaxed mb-4">
              Browser manufacturers provide help pages relating to cookie management in their products:
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {[
                { name: "Google Chrome", url: "https://support.google.com/chrome/answer/95647" },
                { name: "Internet Explorer", url: "https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies" },
                { name: "Mozilla Firefox", url: "https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences" },
                { name: "Safari (Desktop)", url: "https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac" },
                { name: "Safari (Mobile)", url: "https://support.apple.com/en-us/HT201265" },
                { name: "Android Browser", url: "https://support.google.com/nexus/answer/54068" },
                { name: "Opera", url: "https://help.opera.com/en/latest/web-preferences/" },
                { name: "Opera Mobile", url: "https://help.opera.com/en/mobile/android/" }
              ].map((browser) => (
                <a
                  key={browser.name}
                  href={browser.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 p-3 bg-white/5 rounded-lg border border-white/10 hover:border-primary/30 transition-all text-grey hover:text-primary"
                >
                  <Globe className="w-4 h-4 flex-shrink-0" />
                  <span>{browser.name}</span>
                </a>
              ))}
            </div>
          </motion.div>

          {/* Blocking Cookies */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="relative bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10"
          >
            <h2 className="text-2xl font-bold font-dm-sans text-white mb-4">
              Blocking and Disabling Cookies
            </h2>
            <p className="text-grey leading-relaxed">
              Wherever you&apos;re located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser&apos;s help menu for more information.
            </p>
          </motion.div>

          {/* Changes to Policy */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="relative bg-gradient-to-r from-primary/10 to-cyan-500/10 backdrop-blur-sm rounded-2xl p-8 border border-primary/30"
          >
            <h2 className="text-2xl font-bold font-dm-sans text-white mb-4">
              Changes to Our Cookie Policy
            </h2>
            <p className="text-grey leading-relaxed">
              We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated Cookie Policy, you can delete your account.
            </p>
          </motion.div>

          {/* Your Consent */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="relative bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10"
          >
            <h2 className="text-2xl font-bold font-dm-sans text-white mb-4">
              Your Consent
            </h2>
            <p className="text-grey leading-relaxed">
              By using our website, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.
            </p>
          </motion.div>

          {/* Contact Us */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="relative bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10"
          >
            <h2 className="text-2xl font-bold font-dm-sans text-white mb-4">
              Contact Us
            </h2>
            <p className="text-grey leading-relaxed mb-4">
              Don&apos;t hesitate to contact us if you have any questions regarding our Cookie Policy:
            </p>
            <div className="text-grey space-y-2">
              <p><strong className="text-white">Core Innovate IT Ltd</strong></p>
              <p>Email: <a href="mailto:hello@coreinnovate.co.uk" className="text-primary hover:text-cyan-400 transition-colors">hello@coreinnovate.co.uk</a></p>
              <p>Phone: <a href="tel:+441452222192" className="text-primary hover:text-cyan-400 transition-colors">+44 (0) 1452 222192</a></p>
              <p className="leading-relaxed">
                Registered Office: Suite 248, Corinium House, Barnwood Point Business Park, Gloucester, GL4 0XZ, United Kingdom
              </p>
              <p>Company Number: 15566009</p>
            </div>
          </motion.div>

        </div>

        {/* Back Link */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="mt-12 text-center"
        >
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-primary hover:text-cyan-400 transition-colors duration-300 font-semibold"
          >
            ← Back to Home
          </Link>
        </motion.div>
      </div>
    </div>
  )
}
